# Generated by Django 3.2.7 on 2021-10-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='image_profile',
            field=models.TextField(blank=True, null=True, verbose_name='фото'),
        ),
    ]
