# Generated by Django 3.2.7 on 2021-10-21 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20211021_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='image_profile',
        ),
    ]
