# Generated by Django 3.2.7 on 2021-10-26 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_alter_product_price'),
        ('ordersapp', '0002_order_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderItems',
            new_name='OrderItem',
        ),
    ]
